version: '2'
services:
    sandman-app:
        image: sandman
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sandman-mysql:3306/sandman?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    sandman-mysql:
        extends:
            file: mysql.yml
            service: sandman-mysql
